---
- name: Install Zephyr dependencies
  dnf:
    name:
      - '@development-tools'
      - '@c-development'
      - cmake
      - ninja-build
      - gperf
      - dfu-util
      - dtc
      - wget
      - which
      - python3-pip
      - python3-tkinter
      - xz
      - file
      - python3-devel
      - SDL2-devel
      - libusb1-devel 
      - systemd-devel
    state: present
  become: true
